[package]
name = "ritmo_rust"
version = "0.2.0"
edition = "2021"
description = "Núcleo nativo en Rust para Ritmo Music Player: Extractor e Indexador de Metadatos de Audio Audiófilo"

[lib]
name = "ritmo_rust"
crate-type = ["cdylib", "staticlib"]

[dependencies]
# Dependencias estándar del ecosistema Rust para JNI y serialización segura
jni = { version = "0.21", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
